import { spawn, spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { fileURLToPath } from "node:url";

// `npm run dev` starts the backend, listen gateway, Live and Manager against
// the configured A2_AUDIO_DEVICE. `npm run dev:simulate` swaps in the built-in
// test signal, a simulated host output and a simulated Shure AD4Q, and seeds a
// demo showfile in its own data directory, so every monitoring, alert and
// listening path runs without hardware.
// Nothing produced in simulate mode is evidence about real equipment.

const simulate = process.argv.includes("--simulate");
const repoRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));
const SIMULATED_DEVICE = "Pulse test signal";
const SIMULATED_OUTPUT = "Pulse simulated output";
const BACKEND = "http://127.0.0.1:3000";

const backendEnv = simulate
  ? {
      A2_DATA_DIR:
        process.env.A2_DATA_DIR ?? resolve(repoRoot, "data/simulated"),
    }
  : {};
const gatewayEnv = simulate
  ? {
      A2_AUDIO_DEVICE: process.env.A2_AUDIO_DEVICE ?? SIMULATED_DEVICE,
      A2_OUTPUT_DEVICE: process.env.A2_OUTPUT_DEVICE ?? SIMULATED_OUTPUT,
      A2_BACKEND_ORIGIN: process.env.A2_BACKEND_ORIGIN ?? BACKEND,
    }
  : { A2_BACKEND_ORIGIN: process.env.A2_BACKEND_ORIGIN ?? BACKEND };

// Each child leads its own process group so stopping it also stops the
// grandchildren (`npm` → `sh` → `node --watch` → the watched process), which
// otherwise keep their ports after the launcher exits.
function start(args, env = {}) {
  return spawn("npm", args, {
    stdio: "inherit",
    detached: true,
    env: { ...process.env, ...env },
  });
}

/** Runs a shell command inside the listen gateway package. */
function startInGateway(command, env = {}) {
  return spawn("sh", ["-c", command], {
    cwd: resolve(repoRoot, "services/listen-gateway"),
    stdio: "inherit",
    detached: true,
    env: { ...process.env, ...env },
  });
}

if (simulate) {
  // The test signal is generated by pulse-device-capture under the media
  // worker, which also feeds pulse-device-output, so all three binaries are
  // built first. The gateway is built once so the
  // gateway and the receiver simulator never race two compilers into the same
  // dist directory.
  for (const [command, args, cwd] of [
    [
      "cargo",
      [
        "build",
        "--locked",
        "--bin",
        "pulse-device-capture",
        "--bin",
        "pulse-media-worker",
        "--bin",
        "pulse-device-output",
      ],
      repoRoot,
    ],
    ["npm", ["run", "build"], resolve(repoRoot, "services/listen-gateway")],
  ]) {
    const build = spawnSync(command, args, { cwd, stdio: "inherit" });
    if (build.status !== 0) process.exit(build.status ?? 1);
  }
}

const children = [
  start(["run", "dev", "--workspace", "@rvlt/pulse-backend"], backendEnv),
  simulate
    ? startInGateway("node --watch dist/start.js", gatewayEnv)
    : start(
        ["run", "dev", "--workspace", "@rvlt/pulse-listen-gateway"],
        gatewayEnv,
      ),
  start(["run", "dev", "--workspace", "@rvlt/pulse-live"]),
  start(["run", "dev", "--workspace", "@rvlt/pulse-manager"]),
];
if (simulate) {
  children.push(startInGateway("node dist/dev/shure-simulator.js"));
}

let stopping = false;
function stop(signal = "SIGTERM") {
  if (stopping) return;
  stopping = true;
  for (const child of children) {
    try {
      process.kill(-child.pid, signal);
    } catch {
      // The group already exited.
    }
  }
}

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => stop(signal));
}

for (const child of children) {
  child.on("exit", (code, signal) => {
    if (!stopping) {
      process.exitCode = code ?? (signal ? 1 : 0);
      stop();
    }
  });
  child.on("error", (error) => {
    console.error(error);
    process.exitCode = 1;
    stop();
  });
}

/** A demo show over the simulated inputs and receiver, written only into an empty simulate-mode library. */
function demoShowfile(revision) {
  const monitor = { battery: true, rf: true, audio: true };
  const wireless = (id, name, inputIndex, receiverChannel, place) => ({
    id,
    inputIndex,
    name,
    performer: null,
    shureReceiverId: "sim-ad4q",
    shureChannelIndex: receiverChannel,
    micType: "headset",
    imageUrl: null,
    monitor,
    ...place,
  });
  const wired = (id, name, inputIndex, micType, place) => ({
    id,
    inputIndex,
    name,
    performer: null,
    shureReceiverId: null,
    shureChannelIndex: null,
    micType,
    imageUrl: null,
    monitor,
    ...place,
  });
  const ballroom = (categoryId) => ({ roomId: "demo-ballroom", categoryId });
  const breakout = (categoryId) => ({ roomId: "demo-breakout", categoryId });
  return {
    schemaVersion: "0",
    revision,
    updatedAtUtc: null,
    show: { name: "Pulse demo (simulated)" },
    hostOutput: {
      sessions: [
        { id: "demo-comms-a", name: "Comms A", outputChannels: [1] },
        { id: "demo-comms-b", name: "Comms B", outputChannels: [2] },
      ],
    },
    device: { name: SIMULATED_DEVICE, channelCount: 8 },
    shureReceivers: [
      {
        id: "sim-ad4q",
        name: "Simulated AD4Q",
        host: "127.0.0.1",
        model: "AD4Q",
        channelCount: 4,
      },
    ],
    rooms: [
      {
        id: "demo-ballroom",
        name: "Ballroom",
        categories: [
          { id: "demo-stage", name: "Stage" },
          { id: "demo-audience", name: "Audience" },
          { id: "demo-band", name: "Band" },
        ],
      },
      {
        id: "demo-breakout",
        name: "Breakout B",
        categories: [{ id: "demo-lectern", name: "Lectern" }],
      },
    ],
    channels: [
      wireless("demo-lead-vocal", "Lead vocal", 0, 0, ballroom("demo-band")),
      wireless("demo-presenter", "Presenter", 1, 1, ballroom("demo-stage")),
      wireless("demo-guitar", "Guitar", 3, 2, ballroom("demo-audience")),
      wireless("demo-host", "Host", 7, 3, ballroom("demo-stage")),
      wired(
        "demo-line-tone",
        "Line check tone",
        2,
        "other",
        breakout("demo-lectern"),
      ),
      wired(
        "demo-ambient",
        "Ambient mic",
        4,
        "boundary",
        ballroom("demo-audience"),
      ),
      wired("demo-keys", "Keys DI", 5, "instrument", ballroom("demo-band")),
      wired("demo-spare", "Spare", 6, "other", breakout("demo-lectern")),
    ],
    // A short corporate run of show: presenters change per session and the
    // channels a session does not list are expected to be switched off.
    sessions: [
      {
        id: "demo-welcome",
        name: "Welcome and keynote",
        roomId: "demo-ballroom",
        startMinute: 9 * 60,
        channels: [
          { channelId: "demo-host", presenter: "Jordan Ellis" },
          { channelId: "demo-presenter", presenter: "Dana Lee" },
          { channelId: "demo-ambient", presenter: null },
        ],
      },
      {
        id: "demo-panel",
        name: "Panel: the year ahead",
        roomId: "demo-ballroom",
        startMinute: 10 * 60 + 15,
        channels: [
          { channelId: "demo-host", presenter: "Jordan Ellis" },
          { channelId: "demo-presenter", presenter: "Priya Shah" },
          { channelId: "demo-lead-vocal", presenter: "Marcus Webb" },
          { channelId: "demo-guitar", presenter: "Audience Q&A" },
          { channelId: "demo-ambient", presenter: null },
        ],
      },
      {
        id: "demo-close",
        name: "Awards and close",
        roomId: "demo-ballroom",
        startMinute: 11 * 60 + 30,
        channels: [
          { channelId: "demo-host", presenter: "Jordan Ellis" },
          { channelId: "demo-presenter", presenter: "Dana Lee" },
          { channelId: "demo-keys", presenter: null },
          { channelId: "demo-lead-vocal", presenter: "House band" },
        ],
      },
      {
        id: "demo-workshop-1",
        name: "Workshop: planning tools",
        roomId: "demo-breakout",
        startMinute: 9 * 60 + 30,
        channels: [
          { channelId: "demo-spare", presenter: "Sam Ortiz" },
          { channelId: "demo-line-tone", presenter: null },
        ],
      },
      {
        id: "demo-workshop-2",
        name: "Workshop: hiring",
        roomId: "demo-breakout",
        startMinute: 11 * 60,
        channels: [{ channelId: "demo-spare", presenter: "Ana Ruiz" }],
      },
    ],
  };
}

async function seedDemoShowfile() {
  for (let attempt = 0; attempt < 120 && !stopping; attempt += 1) {
    try {
      const response = await fetch(`${BACKEND}/api/v1/showfile`);
      if (response.ok) {
        const current = await response.json();
        if (current.revision !== 0 || current.channels.length > 0) return;
        const saved = await fetch(`${BACKEND}/api/v1/showfile`, {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(demoShowfile(current.revision)),
        });
        console.log(
          saved.ok
            ? "Seeded the simulated demo showfile."
            : `Demo showfile was rejected (HTTP ${saved.status}).`,
        );
        return;
      }
    } catch {
      // The backend is still starting.
    }
    await delay(500);
  }
}

if (simulate) {
  console.log(
    "Simulate mode: Live http://127.0.0.1:4173 · Manager http://127.0.0.1:4174/manager/ · data in data/simulated",
  );
  void seedDemoShowfile();
}
